app/__init__.py
from flask import Flask, render_template
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, render_template, request, jsonify
from models import User, Car, Salesperson, car_schema, all_cars_schema, salesperson_schema, all_sellers_schema, db
from helpers import token_required

api = Blueprint("api", __name__, url_prefix="/api")

@api.route("/testdata")
def testdata():
    return {"Planet": "Earth"}

@api.route("/carinventory", methods = ["POST"])
@token_required
def addcar(current_user_token):
    make = request.json["make"]
    model = request.json["model"]
    year_ = request.json["year_"]
    color = request.json["color"]
    price = request.json["price"]
    user_token = current_user_token.token
    
    print(f"BIG TESTER: {current_user_token}")

    car = Car(make, model, year_, color, price, user_token = user_token)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

@api.route("/carinventory", methods = ["GET"])
@token_required
def displaycarinv(current_user_token):
    owner = current_user_token.token
    cars = Car.query.filter_by(user_token = owner).all()
    response = all_cars_schema.dump(cars)
    return jsonify(response)

@api.route("carinventory/<id>", methods = ["GET"])
@token_required
def displaycar(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        car = Car.query.get(id)
        response = car_schema.dump(car)
        return jsonify(response)
    else:
        return jsonify({"ERROR": "Sorry, valid token required :("}), 401

@api.route("carinventory/<id>", methods = ["POST", "PUT"])
@token_required
def updatecar(current_user_token, id):
    car = Car.query.get(id)
    print("TEST")
    car.make = request.json["make"]
    car.model = request.json["model"]
    car.year_ = request.json["year_"]
    car.color = request.json["color"]
    car.price = request.json["price"]
    car.user_token = current_user_token.token

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

@api.route("carinventory/<id>", methods = ["DELETE"])
@token_required
def deletecar(current_user_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

@api.route("sellers", methods = ["POST"])
@token_required
def addsalesperson(current_user_token):
    first_name = request.json["first_name"]
    last_name = request.json["last_name"]
    email = request.json["email"]
    phone = request.json["phone"]
    street = request.json["street"]
    city = request.json["city"]
    state = request.json["state"]
    zip = request.json["zip"]
    user_token = current_user_token.token

    print(f"BIG TESTER: {current_user_token.token}")

    salesperson = Salesperson(first_name, last_name, email, phone, street, city, state, zip, user_token = user_token)

    db.session.add(salesperson)
    db.session.commit()
    
    response = salesperson_schema.dump(salesperson)
    return jsonify(response)

@api.route("sellers", methods = ["GET"])
@token_required
def displaysellers(current_user_token):
    owner = current_user_token.token
    sellers = Salesperson.query.filter_by(user_token = owner).all()
    response = all_sellers_schema.dump(sellers)
    return jsonify(response)

@api.route("sellers/<id>", methods = ["GET"])
@token_required
def displaysalesperson(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        salesperson = Salesperson.query.get(id)
        response = salesperson_schema.dump(salesperson)
        return jsonify(response)
    else:
        return jsonify({"ERROR": "Sorry, valid token required :("}), 401
    
@api.route("sellers/<id>", methods = ["POST", "PUT"])
@token_required
def updatesalesperson(current_user_token, id):
    salesperson = Salesperson.query.get(id)

    salesperson.first_name = request.json["first_name"]
    salesperson.last_name = request.json["last_name"]
    salesperson.email = request.json["email"]
    salesperson.phone = request.json["phone"]
    salesperson.street = request.json["street"]
    salesperson.city = request.json["city"]
    salesperson.state = request.json["state"]
    salesperson.zip = request.json["zip"]
    salesperson.user_token = current_user_token.token

    db.session.commit()
    response = salesperson_schema.dump(salesperson)
    return jsonify(response)

@api.route("sellers/<id>", methods = ["DELETE"])
@token_required
def deletesalesperson(current_user_token, id):
    salesperson = Salesperson.query.get(id)
    db.session.delete(salesperson)
    db.session.commit()
    response = salesperson_schema.dump(salesperson)
    return jsonify(response)

app/authentication/routes.py
from forms import UserForm, LoginUserForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint("auth", __name__, template_folder="auth_templates")

@auth.route("/signup", methods = ["GET", "POST"])
def signup():
    form = UserForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            password = form.password.data
            print(first_name, last_name, email, password)

            user = User(first_name, last_name, email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a new account. Welcome {first_name} {last_name}, to the MIB Team, I mean the car dealership!", "auth-success")
            return redirect(url_for("site.homepage"))
    except:
        raise Exception("Sorry, invalid form data")

    return render_template("sign_up.html", form=form)

@auth.route("/signin", methods = ["GET", "POST"])
def signin():
    form = LoginUserForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                print("SUCESSFULL")
                flash("You are sucessfully logged in.")
                return redirect(url_for("site.userpage"))
            else:
                print("FAILED 1")
                flash("Access Denied from the Crash-site Actively Radioactive (C.A.R) Dealership")
                return redirect(url_for("auth.signin"))
    except:
        print("FAILED 2")
        raise Exception("Sorry, invalid form data")

    return render_template("sign_in.html", form=form)

@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("site.homepage"))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint("site", __name__, template_folder="site_templates")

@site.route("/")
def homepage():
    return render_template("home.html")

@site.route("/userpage")
def userpage():
    return render_template("user.html")

site.route("/inventory")
def inventory():
    return render_template("inventory.html")

app/templates/base.html
<!-- THIS IS PART OF THE WEBPAGE THAT WILL BE USED EVERYWHERE -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="assets/css/style.css">
<script src="https://kit.fontawesome.com/fe99dd52d4.js" crossorigin="anonymous"></script>
<title>Title</title>
</head>
<body class="bg-dark">
    <nav class="d-flex flex-row p-2 justify-content-between bg-secondary">
        <h1 class="text-warning">THE CAR DEALERSHIP</h1>
        <ul class="list-unstyled d-flex flex-column flex-md-row justify-content-evenly w-25">
            <li class="text-center d-flex flex-column justify-content-center"><h5 class="m-0 p-0"><a class="text-decoration-none text-dark" href="{{ url_for('site.homepage')}}">Home</a></h5></li>
            {% if current_user.is_authenticated %}
            <li class="text-center d-flex flex-column justify-content-center"><h5 class="m-0 p-0"><a class="text-decoration-none text-dark" href="{{ url_for('site.userpage')}}">User</a></h5></li>
            <li class="text-center d-flex flex-column justify-content-center"><h5 class="m-0 p-0"><a class="text-decoration-none text-dark" href="{{ url_for('auth.logout')}}">Logout</a></h5></li>
            {% else %}
            <li class="text-center d-flex flex-column justify-content-center"><h5 class="m-0 p-0"><a class="text-decoration-none text-dark" href="{{ url_for('auth.signup')}}">Sign-Up</a></h5></li>
            <li class="text-center d-flex flex-column justify-content-center"><h5 class="m-0 p-0"><a class="text-decoration-none text-dark" href="{{ url_for('auth.signin')}}">Sign-In</a></h5></li>
            {% endif %}
        </ul>
    </nav>

    <!-- This is where the magic happens! -->
    {% block content %}
    {% endblock %}
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/signin_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div>
            {{ form.email.label }}
            {{ form.email(class="form-control") }}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}
        </div>
    </fieldset>
    {{ form.submit_button(class="btn btn-warning align-items-center m-1 fw-bold") }}
</form>

app/templates/signup_forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <fieldset>
        <div>
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control") }}
        </div>
        <div>
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control") }}
        </div>
        <div>
            {{ form.email.label }}
            {{ form.email(class="form-control") }}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password(class="form-control") }}
        </div>
    </fieldset>
    {{ form.submit_button(class="btn btn-warning align-items-center m-1 fw-bold") }}
</form>